<?php
/**
 * @file
 * Module file for basic_stats.
 */


/**
 * Get number of publishes nodes per content type
 * @param $content_type
 *
 * @return int
 */
function basic_stats_number_nodes($content_type=NULL) {
  $totals = &drupal_static(__FUNCTION__);
  if (!isset($totals[$content_type])) {
    $query = db_select('node', 'n');
    $query->fields('n', array('nid'));
    $query->condition('status', 1, '=');
    if(isset($content_type)) {
      $query->condition('type', $content_type, '=');
    }
    $nodes = $query->execute();

    $totals[$content_type] = $nodes->rowCount();;
  }
  return $totals[$content_type];
}

/**
 * Get number of active users, optional per role
 *
 * @return int
 */
function basic_stats_number_users() {
  $usercount = &drupal_static(__FUNCTION__);
  if(!isset($usercount)) {
    $query = db_select('users', 'u');
    $query->fields('u', array('uid'));
    $query->condition('status', 1, '=');
    $users = $query->execute();
    $usercount = $users->rowCount();
  }
  return $usercount;
}